name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Git remote HEAD
        run: git remote set-head origin --auto

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm test
